### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by bodepd**
This is seriously a WIP, but I wanted to share anyways.

### CODE REVIEW

**Comment by bodepd** [comment]
This is pretty close to being ready for review. I organized it as best I could into logical commit. I need to run another test, but as of now, it can be used to create the exact same deployment scenario that I had working before.

I still need to add back the password generation and data lookup stuff as a custom hiera backend. That will be done in the next week or so. It's obviously not quite the same thing as what you initially created, I'm curious is this is something you are interested in?

**Comment by fghaas** [comment]
Whoa, awesome stuff, thanks! It'll be a few days before I'm done reviewing. Can you check whether it's trivial for you to rebase against current master? I'm sure we can sort things out later, but it would be really nice if we could not break the build between commits, to ease any later bisecting.

**Comment by bodepd** [comment]
it is absolutely non-trivial to rebase against master. My best estimate is that there are probably dozens if not hundreds of individual conflicts to be resolved ;)

**Comment by bodepd** [comment]
I can take a little time tomorrow to see if I can take your master and add the patches that I have by going through the source files one-by-one and modifying the source files. I'm not sure if there is any other reasonable way to converge the branches.

**Comment by bodepd** [comment]
that being said, I'm open to any suggestions about what to do here :)

**Comment by robertstarmer** [comment]
How about we look at the new version and see if it meets our combined needs. If so, perhaps a wholesale reset makes sense? If the idea is good, but there are concerns about how It has been implemented, then there may be value in the high pain path.

Robert

Sent from a device

On Aug 21, 2013, at 5:08 PM, "Dan Bode" <notifications@github.com<mailto:notifications@github.com>> wrote:

that being said, I'm open to any suggestions about what to do here :)

**Comment by bodepd** [comment]
@robertstarmer most of the changes that are leading to the conflicts are caused b/c of a puppet-lint refactor. None of the changes are really bringing it to be closer to the thing that we need. Probably the only path forward is for me to consider this patch set an experiment and start over.

**Comment by bodepd** [comment]
I'm going to close this for now. I've decided to take a different approach with this layer. I may re-open if I decide to resume.

**Pull request closed without merging**
